[2025-01-06T23:29:19.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:29:19.340+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:29:19.342+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-06T23:29:19.438+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_ft_balance> on 2025-01-06 23:28:13.745960+00:00
[2025-01-06T23:29:19.451+0000] {standard_task_runner.py:60} INFO - Started process 454 to run task
[2025-01-06T23:29:19.508+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_insert_log', 'sql_ft_balance', 'manual__2025-01-06T23:28:13.745960+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_insert_log.py', '--cfg-path', '/tmp/tmpr191mumj']
[2025-01-06T23:29:19.514+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask sql_ft_balance
[2025-01-06T23:29:19.742+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:28:13.745960+00:00 [running]> on host 22295d32c47d
[2025-01-06T23:29:20.262+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saida' AIRFLOW_CTX_DAG_ID='dag_insert_log' AIRFLOW_CTX_TASK_ID='sql_ft_balance' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T23:28:13.745960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T23:28:13.745960+00:00'
[2025-01-06T23:29:20.266+0000] {sql.py:276} INFO - Executing: CALL ds.stage_to_ds_ft_balance_f();
[2025-01-06T23:29:20.411+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:29:20.491+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:29:20.934+0000] {sql.py:450} INFO - Running statement: CALL ds.stage_to_ds_ft_balance_f();, parameters: None
[2025-01-06T23:29:21.173+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_insert_log, task_id=sql_ft_balance, execution_date=20250106T232813, start_date=20250106T232919, end_date=20250106T232921
[2025-01-06T23:29:21.453+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T23:29:21.580+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
