[2025-01-06T23:52:58.257+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:52:18.808168+00:00 [queued]>
[2025-01-06T23:52:58.318+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:52:18.808168+00:00 [queued]>
[2025-01-06T23:52:58.322+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-06T23:52:58.371+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_ft_balance> on 2025-01-06 23:52:18.808168+00:00
[2025-01-06T23:52:58.393+0000] {standard_task_runner.py:60} INFO - Started process 869 to run task
[2025-01-06T23:52:58.426+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_insert_log', 'sql_ft_balance', 'manual__2025-01-06T23:52:18.808168+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag_insert_log.py', '--cfg-path', '/tmp/tmpavse02c5']
[2025-01-06T23:52:58.435+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask sql_ft_balance
[2025-01-06T23:52:58.625+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:52:18.808168+00:00 [running]> on host 22295d32c47d
[2025-01-06T23:52:59.109+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saida' AIRFLOW_CTX_DAG_ID='dag_insert_log' AIRFLOW_CTX_TASK_ID='sql_ft_balance' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T23:52:18.808168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T23:52:18.808168+00:00'
[2025-01-06T23:52:59.126+0000] {sql.py:276} INFO - Executing: CALL ds.stage_to_ds_ft_balance_f();
[2025-01-06T23:52:59.213+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:52:59.292+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:52:59.807+0000] {sql.py:450} INFO - Running statement: CALL ds.stage_to_ds_ft_balance_f();, parameters: None
[2025-01-06T23:52:59.956+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_insert_log, task_id=sql_ft_balance, execution_date=20250106T235218, start_date=20250106T235258, end_date=20250106T235259
[2025-01-06T23:53:00.127+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T23:53:00.283+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
