[2025-01-06T23:29:06.775+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_insert_log.ft_posting_f manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:29:06.867+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_insert_log.ft_posting_f manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:29:06.875+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-06T23:29:06.999+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_posting_f> on 2025-01-06 23:28:13.745960+00:00
[2025-01-06T23:29:07.011+0000] {standard_task_runner.py:60} INFO - Started process 429 to run task
[2025-01-06T23:29:07.023+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_insert_log', 'ft_posting_f', 'manual__2025-01-06T23:28:13.745960+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag_insert_log.py', '--cfg-path', '/tmp/tmpbu7kt7xm']
[2025-01-06T23:29:07.025+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask ft_posting_f
[2025-01-06T23:29:07.209+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_insert_log.ft_posting_f manual__2025-01-06T23:28:13.745960+00:00 [running]> on host 22295d32c47d
[2025-01-06T23:29:07.550+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saida' AIRFLOW_CTX_DAG_ID='dag_insert_log' AIRFLOW_CTX_TASK_ID='ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T23:28:13.745960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T23:28:13.745960+00:00'
[2025-01-06T23:29:07.661+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:29:09.908+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-06T23:29:09.920+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_insert_log, task_id=ft_posting_f, execution_date=20250106T232813, start_date=20250106T232906, end_date=20250106T232909
[2025-01-06T23:29:09.959+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T23:29:09.998+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
