[2025-01-06T23:28:49.558+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_insert_log.ft_balance_f manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:28:49.637+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_insert_log.ft_balance_f manual__2025-01-06T23:28:13.745960+00:00 [queued]>
[2025-01-06T23:28:49.674+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-06T23:28:49.863+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-06 23:28:13.745960+00:00
[2025-01-06T23:28:49.918+0000] {standard_task_runner.py:60} INFO - Started process 409 to run task
[2025-01-06T23:28:49.999+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_insert_log', 'ft_balance_f', 'manual__2025-01-06T23:28:13.745960+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_insert_log.py', '--cfg-path', '/tmp/tmpfdg_aw62']
[2025-01-06T23:28:50.039+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask ft_balance_f
[2025-01-06T23:28:50.698+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_insert_log.ft_balance_f manual__2025-01-06T23:28:13.745960+00:00 [running]> on host 22295d32c47d
[2025-01-06T23:28:51.343+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saida' AIRFLOW_CTX_DAG_ID='dag_insert_log' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T23:28:13.745960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T23:28:13.745960+00:00'
[2025-01-06T23:28:51.456+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:28:52.083+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-06T23:28:52.416+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_insert_log, task_id=ft_balance_f, execution_date=20250106T232813, start_date=20250106T232849, end_date=20250106T232852
[2025-01-06T23:28:52.805+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T23:28:53.143+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
